### ISSUE TITLE
API doesn't work in npm3 / node5 / mac

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/place-my-order-api#5]
After running: `donejs api`

```
> place-my-order@0.0.0 api /Users/justin/dev/temp/place-my-order
> place-my-order-api --port 7070

App listening at http://:::7070
Dropped database
Created restaurant Cheese Curd City(32fXaRLXCJeSPowy)
/Users/justin/dev/temp/place-my-order/node_modules/feathers-commons/lib/sockets/helpers.js:55
      info.clients().forEach(function (socket) {
                     ^

TypeError: info.clients(...).forEach is not a function
    at Object.<anonymous> (/Users/justin/dev/temp/place-my-order/node_modules/feathers-commons/lib/sockets/helpers.js:55:22)
```

**Comment by daffl** [comment]
This is a breaking change in a Socket.io patch release (see https://github.com/socketio/socket.io/issues/2368). A fix for Feathers has been added via https://github.com/feathersjs/feathers-commons/commit/858a2647764927b32ecab5b67b1dc4272ad12603 so clearing the cache and reinstalling should solve the issue.

**Comment by justinbmeyer** [comment]
I cleared my cache yesterday.

**Comment by daffl** [comment]
I just tried what I suggested and I don't get an error. The fix came in about an hour before you submitted the issue. If you try again and it is still happening I can look into it again.

**Comment by daffl** [comment]
Actually, there may be a wrong version matcher in the API. I'll double check.

**Comment by daffl** [comment]
Verified. This should be good now.
